name: Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Install and Build
      uses: JamesIves/github-pages-deploy-action@v3
      run: |
        npm install
        npm run build
      with:
        ACCESS_TOKEN: ${{ secrets.DEPLY }}
        BRANCH: gh-pages
        FOLDER: dist